var annotated_dup =
[
    [ "Euclid", null, [
      [ "AABB", "de/d53/classEuclid_1_1AABB.html", "de/d53/classEuclid_1_1AABB" ],
      [ "Camera", "d7/d29/classEuclid_1_1Camera.html", "d7/d29/classEuclid_1_1Camera" ],
      [ "CommonPlyReader", "d0/dbb/classEuclid_1_1CommonPlyReader.html", "d0/dbb/classEuclid_1_1CommonPlyReader" ],
      [ "CommonPlyWriter", "db/d19/classEuclid_1_1CommonPlyWriter.html", "db/d19/classEuclid_1_1CommonPlyWriter" ],
      [ "GeodesicsInHeat", "de/d8d/classEuclid_1_1GeodesicsInHeat.html", "de/d8d/classEuclid_1_1GeodesicsInHeat" ],
      [ "HKS", "d8/d39/classEuclid_1_1HKS.html", "d8/d39/classEuclid_1_1HKS" ],
      [ "Holomorphic_one_forms_parameterizer3", "d2/dee/classEuclid_1_1Holomorphic__one__forms__parameterizer3.html", "d2/dee/classEuclid_1_1Holomorphic__one__forms__parameterizer3" ],
      [ "Light", "d3/d77/structEuclid_1_1Light.html", "d3/d77/structEuclid_1_1Light" ],
      [ "Material", "da/db2/structEuclid_1_1Material.html", "da/db2/structEuclid_1_1Material" ],
      [ "OBB", "db/d77/classEuclid_1_1OBB.html", "db/d77/classEuclid_1_1OBB" ],
      [ "OrthoRasCamera", "df/d1c/classEuclid_1_1OrthoRasCamera.html", "df/d1c/classEuclid_1_1OrthoRasCamera" ],
      [ "OrthoRayCamera", "d9/de5/classEuclid_1_1OrthoRayCamera.html", "d9/de5/classEuclid_1_1OrthoRayCamera" ],
      [ "PerspRasCamera", "df/d5b/classEuclid_1_1PerspRasCamera.html", "df/d5b/classEuclid_1_1PerspRasCamera" ],
      [ "PerspRayCamera", "db/dd2/classEuclid_1_1PerspRayCamera.html", "db/dd2/classEuclid_1_1PerspRayCamera" ],
      [ "PlyCharProperty", "d3/dba/classEuclid_1_1PlyCharProperty.html", "d3/dba/classEuclid_1_1PlyCharProperty" ],
      [ "PlyDoubleProperty", "d8/d53/classEuclid_1_1PlyDoubleProperty.html", "d8/d53/classEuclid_1_1PlyDoubleProperty" ],
      [ "PlyElement", "d7/d9f/classEuclid_1_1PlyElement.html", "d7/d9f/classEuclid_1_1PlyElement" ],
      [ "PlyFloatProperty", "d3/d7a/classEuclid_1_1PlyFloatProperty.html", "d3/d7a/classEuclid_1_1PlyFloatProperty" ],
      [ "PlyHeader", "df/df1/classEuclid_1_1PlyHeader.html", "df/df1/classEuclid_1_1PlyHeader" ],
      [ "PlyIntProperty", "d5/d86/classEuclid_1_1PlyIntProperty.html", "d5/d86/classEuclid_1_1PlyIntProperty" ],
      [ "PlyProperty", "de/dd0/classEuclid_1_1PlyProperty.html", "de/dd0/classEuclid_1_1PlyProperty" ],
      [ "PlyReader", "d2/d6e/classEuclid_1_1PlyReader.html", "d2/d6e/classEuclid_1_1PlyReader" ],
      [ "PlyShortProperty", "d7/d79/classEuclid_1_1PlyShortProperty.html", "d7/d79/classEuclid_1_1PlyShortProperty" ],
      [ "PlyUcharProperty", "d5/da8/classEuclid_1_1PlyUcharProperty.html", "d5/da8/classEuclid_1_1PlyUcharProperty" ],
      [ "PlyUintProperty", "d1/dd5/classEuclid_1_1PlyUintProperty.html", "d1/dd5/classEuclid_1_1PlyUintProperty" ],
      [ "PlyUshortProperty", "dd/d22/classEuclid_1_1PlyUshortProperty.html", "dd/d22/classEuclid_1_1PlyUshortProperty" ],
      [ "PlyWriter", "df/d2d/classEuclid_1_1PlyWriter.html", "df/d2d/classEuclid_1_1PlyWriter" ],
      [ "ProPtr", "d7/daa/classEuclid_1_1ProPtr.html", "d7/daa/classEuclid_1_1ProPtr" ],
      [ "RasCamera", "d7/da8/classEuclid_1_1RasCamera.html", "d7/da8/classEuclid_1_1RasCamera" ],
      [ "Rasterizer", "d5/d8f/classEuclid_1_1Rasterizer.html", "d5/d8f/classEuclid_1_1Rasterizer" ],
      [ "RayCamera", "da/d7a/classEuclid_1_1RayCamera.html", "da/d7a/classEuclid_1_1RayCamera" ],
      [ "RayTracer", "dc/d40/classEuclid_1_1RayTracer.html", "dc/d40/classEuclid_1_1RayTracer" ],
      [ "RemeshDelaunayVisitor", "df/d0b/structEuclid_1_1RemeshDelaunayVisitor.html", "df/d0b/structEuclid_1_1RemeshDelaunayVisitor" ],
      [ "Ricci_flow_parameterizer3", "d7/d74/classEuclid_1_1Ricci__flow__parameterizer3.html", "d7/d74/classEuclid_1_1Ricci__flow__parameterizer3" ],
      [ "RicciFlowSolverSettings", "de/d9f/structEuclid_1_1RicciFlowSolverSettings.html", "de/d9f/structEuclid_1_1RicciFlowSolverSettings" ],
      [ "SCP_parameterizer_3", "da/d6d/classEuclid_1_1SCP__parameterizer__3.html", "da/d6d/classEuclid_1_1SCP__parameterizer__3" ],
      [ "SpinImage", "df/d09/classEuclid_1_1SpinImage.html", "df/d09/classEuclid_1_1SpinImage" ],
      [ "SplitSite", "d4/d25/structEuclid_1_1SplitSite.html", "d4/d25/structEuclid_1_1SplitSite" ],
      [ "Timer", "d0/d3f/classEuclid_1_1Timer.html", "d0/d3f/classEuclid_1_1Timer" ],
      [ "Transform", "da/d31/structEuclid_1_1Transform.html", "da/d31/structEuclid_1_1Transform" ],
      [ "ViewSphere", "d3/d05/classEuclid_1_1ViewSphere.html", "d3/d05/classEuclid_1_1ViewSphere" ],
      [ "WKS", "da/d08/classEuclid_1_1WKS.html", "da/d08/classEuclid_1_1WKS" ]
    ] ]
];